---
title: "sistmr : Mode d'emploi"
author: "Equipe SISTM"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

`sistmr` est un package R, hébergé sur Github, contenant des fonctions
communes aux membres de l'équipe [SISTM](bph.center/les-equipes/statistiques-pour-la-medecine-translationnelle-sistm/).

# Philosophie

Ce package contient des fonctions utilisées par un ou plusieurs membres de
l'équipe. Il permet de rassembler dans un même dépôt des codes R utiles
à différents membres de l'équipe et d'héberger la dernière version de ces
codes.

# En pratique

## Github

Pour pouvoir contribuer, il faut:

- se créer un compte sur [Github](https://github.com/)

- demander de faire partie de l'"organisation" SISTM : https://github.com/sistm

- cloner le dépôt git https://github.com/sistm/sistmr (par exemple, depuis
Rstudio : New project > Version control > Git, renseigner l'adresse du dépôt
dans "Repository URL" puis "Create project").

Pour plus d'informations sur l'utilisation de Git et Github, voir le chapitre 2
de [https://r-dev-perf.borishejblum.science](https://r-dev-perf.borishejblum.science/controle-de-version-avec-git-et-github-hitorique-de-changement.html).

## Code R

Une fois l'accès configuré, l'essentiel des contributions se passe dans le
dossier `R/`. La marche à suivre et les recommandations sont les suivantes :

- LA REGLE : une fonction = un fichier `*.R` !!!

- ajouter un fichier R contenant le code R de la fonction

- documenter la fonction à l'aide des tags `roxygen` (pour plus de détails sur
la documentation `roxygen`, voir la section 1.3 de [https://r-dev-perf.borishejblum.science](https://r-dev-perf.borishejblum.science/construire-un-package-r.html#documenter-une-fonction)),
puis générer la documentation (Rstudio: onglet Build > More > Document, ou
exécuter `devtools::document()`)

## Prise en compte des modifs et synchronisation

Le travail est fait en local, il faut maintenant le synchroniser avec le 
serveur :

- faire un "commit", en explicitant au maximum ce que vous avez fait

- faire un "push" pour uploader vos modifications vers github.

Merci de votre contribution à `sistmr` :-)